[project]
name = "qt-extensions"
version = "0.1.4"
description = "Various QtWidgets extending the functionality of PySide2"
authors = [
    {name = "Beat Reichenbach"}
]
dependencies = [
    "PySide2",
    "typing_extensions"
]
requires-python = ">=3.9, <3.11"
license = {text = "MIT"}
readme = "README.md"

[project.optional-dependencies]
dev = ["python-semantic-release"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["qt_extensions*"]

[tool.semantic_release]
version_variable = "qt_extensions/__init__.py:__version__"
branch = "main"
upload_to_pypi = false
upload_to_repository = false
upload_to_release = false
version_toml = "pyproject.toml:project.version"
